# Usamos la imagen base con JDK 8 (debes haberla creado o descargado previamente)
FROM oracle/jdk:8

# Variables de entorno para WebLogic
ENV ORACLE_HOME=/u01/oracle \
    USER_MEM_ARGS="-Djava.security.egd=file:/dev/./urandom" \
    PATH=$PATH:${JAVA_HOME}/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin

# Copiamos los instaladores y scripts al contenedor
COPY fmw_12.2.1.4.0_wls_quick_Disk1_1of1.zip /u01/
COPY install.file oraInst.loc /u01/
COPY container-scripts/createAndStartEmptyDomain.sh /u01/oracle/
COPY container-scripts/create-wls-domain.py        /u01/oracle/
COPY container-scripts/get_healthcheck_url.sh       /u01/oracle/

# Creamos el usuario 'oracle' y ajustamos permisos
# NOTA: quitamos el 'mkdir /u01' para evitar errores si ya existe
RUN useradd -b /u01 -d /u01/oracle -m -s /bin/bash oracle && \
    chown oracle:root -R /u01 && \
    chmod -R 775 /u01

# Pasamos a 'oracle' para instalar WebLogic
USER oracle

# Extraemos e instalamos WebLogic
RUN cd /u01 && \
    ${JAVA_HOME}/bin/jar xf /u01/fmw_12.2.1.4.0_wls_quick_Disk1_1of1.zip && \
    ${JAVA_HOME}/bin/java -jar /u01/fmw_12.2.1.4.0_wls_quick.jar \
    -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc \
    -ignoreSysPrereqs -force -novalidation ORACLE_HOME=/u01/oracle && \
    rm /u01/fmw_12.2.1.4.0_wls_quick_Disk1_1of1.zip /u01/install.file && \
    rm -rf /u01/oracle/cfgtoollogs

# Ajustamos permisos de los scripts
RUN chmod +x /u01/oracle/createAndStartEmptyDomain.sh \
             /u01/oracle/get_healthcheck_url.sh && \
    chown oracle:root /u01/oracle/createAndStartEmptyDomain.sh \
                      /u01/oracle/create-wls-domain.py \
                      /u01/oracle/get_healthcheck_url.sh

# Definimos el directorio de trabajo y exponemos los puertos
WORKDIR /u01/oracle
EXPOSE 7001 9002

# Ejecutamos el script de arranque por defecto
CMD ["/u01/oracle/createAndStartEmptyDomain.sh"]
